andanteyk/ElectronicObserver

- ElectronicObserver/Window/FormMain.cs
ちょっと使い方が悪かったのかもしれませんが、以下の様なエラーが出ていたので修正しました。あと、OpenWriteは長いファイルに短いファイルを上書きすると、新旧のデータが混在するそうなので、そこも修正しました。お使い頂ければ幸いです。
エラーレポート : 2015/03/13 21:50:05
エラー : IOException
以前に作成されたエントリが開いているときはエントリを作成できません。
追加情報 : ウィンドウ レイアウトの保存に失敗しました。
スタックトレース：
場所 System.IO.Compression.ZipArchive.AcquireArchiveStream(ZipArchiveEntry entry)
場所 System.IO.Compression.ZipArchiveEntry..ctor(ZipArchive archive, String entryName)
場所 System.IO.Compression.ZipArchive.DoCreateEntry(String entryName, Nullable`1 compressionLevel)
場所 System.IO.Compression.ZipArchive.CreateEntry(String entryName)
場所 ElectronicObserver.Window.FormMain.SaveLayout(String path) 場所 x:\Switch\Visual Studio 2012\Projects\ElectronicObserver\ElectronicObserver\Window\FormMain.cs:行 384
> ウィンドウレイアウトの保存に失敗することがあったので修正

- ElectronicObserver/Notifier/NotifierManager.cs
- ElectronicObserver/Observer/APIObserver.cs
- ElectronicObserver/Utility/Logger.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.cs
- ElectronicObserver/Window/FormArsenal.cs
- ElectronicObserver/Window/FormBattle.cs
- ElectronicObserver/Window/FormBrowserHost.cs
- ElectronicObserver/Window/FormCompass.cs
- ElectronicObserver/Window/FormDock.cs
- ElectronicObserver/Window/FormFleet.cs
- ElectronicObserver/Window/FormFleetOverview.cs
- ElectronicObserver/Window/FormHeadquarters.cs
- ElectronicObserver/Window/FormInformation.cs
- ElectronicObserver/Window/FormLog.cs
- ElectronicObserver/Window/FormMain.cs
- ElectronicObserver/Window/FormQuest.cs
- ElectronicObserver/Window/FormShipGroup.cs
通信とGUI更新を非同期に行うことで通信レスポンスを改善しました。
通信スレッドはAPIObserverのFiddlerイベントハンドラ２つに押し込めて、他は基本全てGUIスレッドで処理しています。Fiddlerイベントハンドラのファイル書き込み部分は別スレッド化しました。Loggerのスレッド間の競合が起こりそうな部分にロックの追加と、必要なくなったInvoke呼び出しの廃止も行っています。
お使い頂ければ幸いです。
> ゲームのレスポンスを改善

- .gitmodules
- ElectronicObserver.sln
- ElectronicObserver/ElectronicObserver.csproj
フロートウィンドウを動かした時、アウトラインしか動かない動作には違和感があったので、ウィンドウ自体が動くようにしました。ライブラリを修正する必要があったため、DockPanelSuiteをサブモジュールとして追加しています。checkoutしたあと、submodule updateしてください
DockPanelSuiteはv2.9→最新のmasterブランチ(v3.0)にバージョンアップしています。タブを切り替えた時にちらつく問題が解消されているようです。
お使い頂ければ幸いです。
> フロートウィンドウを動かした時にウィンドウが動くようにしました。

- ElectronicObserver/Utility/Mathematics/DateTimeHelper.cs
小さな修正です。
参考) UNIX時間からDateTimeへの変換
http://smdn.jp/programming/netfx/tips/convert_unixtime_into_datetime/
> マシンのタイムゾーン設定によって残り時間が正しく表示されない問題を修正

- ElectronicObserver/Data/FleetData.cs
- ElectronicObserver/Utility/Data/Calculator.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.Designer.cs
- ElectronicObserver/Window/FormFleet.cs
2-5新秋簡易式に対応してみました。
詳細は http://nekokan333.blog.fc2.com/blog-entry-345.html にありますが、
要するに、ほっぽアルファさんで採用されている索敵値計算式です。
ついでに、ツールチップで各索敵値を並べて確認できるようにしてあります。
もしよければ取り込んでくださいませ。
> 2-5新秋簡易式対応

- Browser/Browser.csproj
- Browser/Dpi.cs
- Browser/FormBrowser.cs
- Browser/ScreenHelper.cs
拾い物ですが、DPIが100%でない時への対応です。
Flash抽出失敗は私のところだと以下の環境で再現しました
- Windows 8.1
画面解像度→テキストやその他の項目の大きさの変更 で
- 中 - 125%
- すべてのディスプレイで同じ拡大率を使用するをチェック
> Flash抽出に失敗することがあるのを修正

- ElectronicObserver/Window/FormShipGroup.Designer.cs
- ElectronicObserver/Window/FormShipGroup.cs
艦船グループのShipViewのコンテキストメニューで、編成中の艦隊をグループに追加する機能を追加しました。
ChangeShipViewメソッドがタブの切り替えとShipView構築で一体になっていたため、ShipView構築の部分を分離してBuildShipViewメソッドを作成し、上記機能に使用しています。
※前回からの差異：ブランチの切り直し・グループ追加処理を改善
> 艦船グループ: 編成中の艦隊をグループに追加する機能

- Browser/FormBrowser.cs
一部COM呼び出しでエラーが発生することがあるので（原因は不明）ラッパーオブジェクトを使うように修正しました。
> Win7で再読み込み後にSSに失敗することがあるのを修正

- ElectronicObserver/Data/Battle/BattleCombinedAirBattle.cs
- ElectronicObserver/Data/Battle/BattleCombinedNightOnly.cs
- ElectronicObserver/Data/Battle/BattleCombinedNormalDay.cs
- ElectronicObserver/Data/Battle/BattleCombinedNormalNight.cs
- ElectronicObserver/Data/Battle/BattleCombinedWater.cs
Once there's a boat's hp less then 0 in the second fleet, it will occur an error in the battle.
Because of the count of members can not larger than 6.
Sorry for my poor english.  -Q-
> There might be a boundary exception in the combined battle.

- ElectronicObserver/Window/FormShipGroup.cs
艦これ起動前に艦船グループのタブを選択した場合、艦これ起動後に選択していたグループの所属艦情報が消滅してしまう問題を修正しました。
> 艦これ起動前に艦船グループのタブを選択した場合の問題を修正

- ElectronicObserver/ElectronicObserver.csproj
- ElectronicObserver/Observer/APIKancolleDB.cs
- ElectronicObserver/Observer/APIObserver.cs
- ElectronicObserver/Utility/Configuration.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.Designer.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.cs
ユーザーはkancolle-db.netに貢献したい場合。
この機能を実現することができます。
デフォルトではオフになって、ユーザーが設定を開くことができます。
アクセスキーを入力し、通信が（api_tokenが除去されている）kancolle-db.netに送信することができる。
さらに詳しい情報は[kancolle-db.net](http://kancolle-db.net)見つけることができます。
この機能を追加することができた場合は非常に感謝されます。
> ユーザーはkancolle-db.netにデータを送信するように選択することができます

- ElectronicObserver/Resource/Record/ResourceRecord.cs
戦果計算でResourceRecordを検索するとき、指定した検索日時よりも１つ古いレコードを返却する問題を修正しました。
> ResourceRecordの検索時に、検索日時よりも１つ古いレコードを返却する問題を修正

- ElectronicObserver/Window/FormInformation.cs
2015/5/29のアップデートで、艦船図鑑のページ選択時に受信する艦船が50隻から70隻に拡張されたため対応しました。
> 艦船図鑑の受信艦船数70隻への拡張に対応

- ElectronicObserver/Data/Quest/ProgressAGo.cs
進捗欄に対してあ号の表示内容が大きすぎ、未消化の部分が「...」となってしまって後は何をすればいいのかが一目でわからない！ という問題があるので、進捗が悪い順に表示するようにしてみました。
よろしければ取り込んでくださいませ。
> あ号作戦の進捗表示の詳細を、進捗の悪い要素順にしてみた

- ElectronicObserver/Window/Dialog/DialogResourceChart.cs
期間内にレコードが存在しない場合、GetRecords()で空集合が返却されてエラーとなっていた問題を修正しました。
また、グラフのプロットが1個も存在しない場合max,minの計算でエラーになるため、グラフの最後に現在の資源量を挿入するよう変更しました。
> 資源チャート: 指定期間内のレコードが存在しない場合にエラーとなる問題を修正

- Browser/FormBrowser.cs
これは、条件が常にfalseです原因になります。
リファレンス：https://msdn.microsoft.com/ja-jp/library/system.uri.absolutepath.aspx
> Uri.AbosultePath パス情報には、URI のスキーム、ホスト名、およびクエリ部分は含まれていません。

- ElectronicObserver/Window/FormInformation.cs
before|after
---|---
*font changes after non-<br>Japanese characters | *font stays on Meiryo UI<br>(default MainFont)
> 情報：フォントの自動変更を抑制する

- Browser/FormBrowser.cs
- Browser/Properties/Resources.resx
This pull request does the following:
1. **Prevent Browser position reset when SizeAdjuster size is 0**  
Some time when 74EO is running in background (like minimized) SizeAdjuster of BrowserHost may return 0, this makes Browser move to incorrect position (while stylesheet applied).
2. **Prevent Browser position & size reset when navigate to login page**  
Only reset position & size it navigate to login page without applying stylesheet (the same as refresh)
3. **Use native JavaScript instead of jQuery for FrameScript & PageScript**  
Prevents error when jQuery library is not loaded while trying to apply stylesheet.
---
As a matter of fact, I found that you can simply remove entire ```private void Browser_DocumentCompleted``` section in ```FormBrowser.cs``` and/or the corespoding line in …
> Browser: Improve User Experience 2

- ElectronicObserver/Window/FormBattle.cs
Sorry for over-fixing in #90 , it causes a problem that hp bars in practice is not shown correctly.
Now only the friend escort fleet will get max hp from fleet data, please check
> Change method of getting Max hp

- ElectronicObserver/Window/Dialog/DialogBattleDetail.cs
戦闘詳細の一部が特定のレイアウト環境で画面外に表示される不具合を修正しました。
具体的には戦闘ウィンドウあるいは右クリックがモニター画面の右端や下端の付近にあるときに発生します。
これは表示位置が `FormBattle.cs` （1131行） でコンテキストメニューの座標で指定されているためです。
dialog.Location = RightClickMenu.Location;
上記の解決のため `DialogBattleDetail.cs` にて実際のダイアログのサイズを取得したのち表示位置の再指定を行うよう調整しています。
> 戦闘詳細：画面外に表示される不具合を修正

- Browser/FormBrowser.cs
- Browser/Properties/Resources.Designer.cs
- Browser/Properties/Resources.resx
- BrowserLib/IBrowser.cs
- BrowserLib/IBrowserHost.cs
- ElectronicObserver/Utility/Configuration.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.Designer.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.cs
- ElectronicObserver/Window/FormBrowserHost.cs
DMMのゲーム画面にて表示されるページ更新ダイアログを表示させない機能を追加しました。
具体的な方法は下記の confirm メソッド を含む function 関数 を上書きすることで実現しています。
reloadDialog : function() {
if (confirm("エラーが発生したため、ページ更新します。")) {
location.reload();
}
}
おそらく多重ログインを防止するために組み込んであるのですが誤更新してしまう原因にもなります。
なのでデフォルトとしてではなく設定から任意で機能のオンオフを切り替えができるように設計してあります。
なお参考までに reloadDialog 関連の JavaScript コード を添付しておきます。
[reloadDialog.txt](https://github.com/andanteyk/ElectronicObserver/files/671244/reloadDialog.txt)
> ブラウザ：DMMによるページ更新ダイアログの非表示を可能に

- ElectronicObserver/Utility/Configuration.cs
- ElectronicObserver/Window/Control/ShipStatusEquipment.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.Designer.cs
- ElectronicObserver/Window/Dialog/DialogConfiguration.cs
- ElectronicObserver/Window/FormFleet.cs
This PR adds an option so the user can choose to display aircraft level as digits (1, 2, etc.) instead of icons (|, ||, etc.).
Preview:
When aircraft has 改修レベル, two digits will overlap and it is difficult to see them. Probably we should find a better way to display them when they are both present?
> Add an option to display aircraft level as digits instead of icons

- ElectronicObserver/Window/Integrate/FormIntegrated.cs
On a x64 platform, casting a `IntPtr` directly to `uint` will result in a `System.OverflowException` if the value of that `IntPtr` is more than `0x7FFFFFFF`.
When doing such casting, `IntPtr` is actually first casted to `int` and then casted to `uint` (confirmed by checking IL code generated by compiler). The casting from `IntPtr` to `int` is implemented as
```c#
public unsafe static explicit operator int (IntPtr  value) 
{
#if WIN32
return (int)value.m_value;
#else
long l = (long)value.m_value;
return checked((int)l);
#endif
}
```
Let's say we have a `IntPtr` of value `0xFFFFFFFF`. On a x86 system it will get casted to `-1` as a `int` and when later casted again to `uint`, it gets back to `0xFFFFFFFF` as expected. On a x64 system however, it is actually doing a `checked` casting from …
> Cast IntPtr to long before casting it to uint

- ElectronicObserver/Window/FormMain.cs
This PR hopefully will fix #91.
According to http://stackoverflow.com/a/16343373, task bar might not be updated properly if `Text` property is changed during `Form_Load`.
The solution provided was to use `BeginInvoke`, which actually just changes the execution order. With this the block will get executed some time before/after `Form_Shown` (definitely after `Form_Load` though). So I am just moving the line to `Form_Shown` and hopefully this will work.
A side effect is that user will now see the caption to be '試製七四式電子観測儀' during startup and it will be changed to the proper value after the loading is completed.
> Move setting Text to Form_Shown

- ElectronicObserver/Other/Information/apilist.txt
The newly added API can be confirmed with 新型砲熕兵装資材. Although I currently have no response log for ネ式エンジン, I think it should be the same.
> add api for useitem in item improvement detail

- ElectronicObserver/Notifier/NotifierBase.cs
- ElectronicObserver/Window/Dialog/DialogConfigurationNotifier.cs
通知ダイアログの設定で
- 表示位置を入力
- テスト通知で確認
- ずれてたら修正
- …………
とするのが煩わしかったので、
テスト通知ダイアログを表示したい位置に移動させて閉じればその位置に表示するよう設定する機能を追加しました。
ただし、「配置」を「手動（絶対）」に設定した場合だけ動作するようにしています（それ以外の場合は未検証です）。
> 通知ダイアログの配置を「手動（絶対）」にした場合にテスト通知ダイアログを移動することで表示位置設置を変更できる機能を追加

- ElectronicObserver/App.config
- ElectronicObserver/Utility/Data/RecordHash.cs
This is a follow-up for #110. Changes in this PR:
* Allow ignoring system FIPS settings (again). We should generally prefer the system implementation if possible, which provides much better performance.
* Catch any kind of `Exception` in `RecordHash`. In a perfect world we would be catching only `InvalidOperationException` and `TargetInvocationException`, but C# unfortunately does not support multi-catch and I don't feel too bad to just catch-all here.
(.Net might be doing reflection when initializing the hasher, so the exception might be a `TargetInvocationException` with `InvalidOperationException` as `InnerException`)
> Ignore FIPS Policy (Again)

- ElectronicObserver/Utility/Mathematics/DateTimeHelper.cs
> 残り時間を文字列に変換する時、秒単位で切り上げする

- ElectronicObserver/Data/ShipGroup/ExpressionData.cs
```C#
case ExpressionOperator.EndWith:    // returns memberex.LastIndexOf( constex ) == ( memberex.Length - constex.Length )
condex = Expression.Equal(
Expression.Call(memberex, typeof(string).GetMethod("LastIndexOf", new Type[] { typeof(string) }), constex),
Expression.Subtract(Expression.PropertyOrField(memberex, "Length"), Expression.PropertyOrField(constex, "Length")));
break;
```
例えば艦名は「ＸＸＸＸ（**４文字**）で終わる」を条件にするど、入力内容をかかわらす、艦名は**３文字**の艦はすべてこの条件にあたる（```LastIndexOf = -1``` ) 。修正可能だが、そもそもなぜ ```EndsWith``` でわなく、こういう面倒な方法を選んだし…
「から始まる」・「から始まらない」についで、同じような誤動作の可能性はないが、一応 ```StartsWith``` にかわりました。
> グループ：「で終わる」・「で終わらない」条件を含むフィルタが誤動作しないよに

- ElectronicObserver/Data/Battle/Detail/BattleDetail.cs
通常出撃にわ特に問題ないが、演習において相手側同じ艦娘がいる場合、どっちがどっちに攻撃しているがよくわからなくなる。この問題を解消するため、味方艦常に左側に置きます。
航空戦について、攻撃側の表印は「敵軍航空隊」・「自軍航空隊」なんで、この問題は存在しません。支援攻撃について、敵軍支援攻撃まだ無い、例え今後あるどすれば、航空戦同様に攻撃側の表印で区別つかれる。それゆえ、航空戦・支援攻撃には変化なし（防御側か右側に置く）。
> 戦闘詳細：攻撃方向表示するとき、味方艦を左側に置く

- ElectronicObserver/Window/Dialog/DialogAntiAirDefense.Designer.cs
- ElectronicObserver/Window/Dialog/DialogAntiAirDefense.cs
敵スロット機数を直接入力する時なぜが ```EnemySlotCount.Value``` Null になる、~~代わりに ```int.Parse(EnemySlotCount.Text)``` 使います。~~ まだ、最小値を０から１に変更。
> 対空砲火詳細：敵スロット機数直接入力すると落ちる不具合を修正

- ElectronicObserver/Window/Dialog/DialogResourceChart.cs
*スクリーンショットは私のバージョンからのものですが、このＰＲには日本語で「高速修**復**材」で書かれています
> 資源チャート：資源、資源(差分)チャートに高速修復材を追加

- ElectronicObserver/Window/Dialog/DialogShipGroupFilter.cs
なぜ ```is DataGridViewCheckBoxColumn``` の判断を付けたし？
> DialogShipGroupFilter：コンボボックスの更新を即時反映する

- ElectronicObserver/Utility/Data/Calculator.cs
・25種、28種：日向改二
・32種：金剛改二丙、Warspite、Warspite改、Ark Royal、Ark Royal改
・34～37種：Fletcher、Fletcher改
> 対空CIの対応艦を追加

- ElectronicObserver/Data/ShipData.cs
- ElectronicObserver/Utility/Data/Calculator.cs
* 爆装を基本攻撃力に加算するように変更（https://twitter.com/wedge503/status/1123528702220890113）
* 彗星一二型(三一号光電管爆弾搭載機)の夜間攻撃力計算式は岩井爆戦のものと同様（https://kancolle.fandom.com/wiki/Combat?oldid=1097460#/Damage_Calculation ※爆装の加算は反映されていない模様）
* 空母夜襲CIは従来の組み合わせに加えて、夜間爆撃機1↑＋(夜間戦闘機＋夜間攻撃機)1↑で発生（https://kancolle.fandom.com/wiki/Combat?oldid=1097460#/Night_Battle）
命名規則：
* 夜間対応爆撃機（Night Capable Bomber）：零戦62型(爆戦/岩井隊)
* 夜間爆撃機（Night Bomber）：彗星一二型(三一号光電管爆弾搭載機)
> 彗星一二型(三一号光電管爆弾搭載機)の空母夜襲対応

- ElectronicObserver/Utility/Mathematics/DateTimeHelper.cs
- ElectronicObserver/Window/FormMain.cs
Fix a bug that monthly/quarterly quests sometimes does not reset for a time zone that is more than 5 hours late than Japan.
日本より5時間以上遅いタイムゾーンでは、マンスリー/クォータリー任務がリセットされないことがあるバグを修正します。
The bug will happen when user refresh the quest list after new monthly quest refreshes but the local time is not yet in the new month. e.g. When Japan is 09/01 6:00 (monthly quest reset at 5:00), an user in UTF+0 will have local time 08/31 21:00, the previous algorithm will think the month is still 08 and set border time to be 07/31 20:00 (=08/01 5:00 Japan time) which is wrong. New algorithm will fix it as it convert all time to Japan time, no more local time.
> Fix a time zone related quest fail-to-reset bug. 

- ElectronicObserver/Data/ShipData.cs
1. 日向改二の先制対潜条件を「回転翼機（カ号観測機, オ号観測機改, オ号観測機改二）の合計が2個以上」もしくは「対潜ヘリ（S-51J, S-51J改）が1個以上」に修正
1. Jervis改と同様にJanus改を無条件で先制対潜可能と判定するように変更
> 日向改二の先制対潜条件の修正／Janus改の自動先制対潜への対応

- BrowserLib/PipeCommunicator.cs
- ElectronicObserver/Window/FormBrowserHost.cs
Also made sure to generate an error report if Browser connection fails at startup time.
In some cases we see `ブラウザプロセスが予期せず終了しました。` immediately after startup, but the Browser is actually running and one can even continue using it without problem. It seems to happen more often when EO is compiled in release mode.
After fixing this retry logic I cannot reproduce it anymore. Likely this is because of some race condition, which I am too lazy to dig in...
> Don't throw NullReferenceException during handling of CommunicationException

- ElectronicObserver/Other/Information/apilist.txt
- 107: North Carolina級 (Used by Washington)
- 108: Town級 (Used by Sheffield)
> Add new api_ctype for ships.

- ElectronicObserver/Data/ShipData.cs
ソース：https://twitter.com/nishikkuma/status/1366364071193309185?s=20
昼砲撃戦キャップ：220
昼雷撃戦キャップ：180
夜戦キャップ：360
対潜キャップ：170
航空戦キャップ：170
支援キャップ：170
> 砲撃、雷撃、対潜、航空攻撃、夜戦のキャップ更新
